# Generated by Django 3.2.10 on 2021-12-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaidApp', '0002_auto_20211218_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemMetadata',
        ),
    ]
